FROM opensuse/leap:15.2

MAINTAINER Lemures Lemniscati <lemures.lemniscati@gmail.com>

RUN date --iso-8601=ns\
 && zypper --non-interactive update\
 && zypper --non-interactive \
      install --no-recommends --oldpackage\
	bash\
	diffutils\
	findutils\
	git\
	make\
	gzip\
	bzip2\
	xz\
	tar\
	gcc\
	lua53 lua53-devel lua53-luarocks\
	lua51 lua51-devel lua51-luarocks\
 && date --iso-8601=ns
