FROM fedora:33

LABEL maintainer="Lemures Lemniscati <lemures.lemniscati@gmail.com>"

RUN date --iso-8601=ns\
 && yum -y update\
 && yum -y install\
	tzdata\
	bash\
	diffutils\
	findutils\
	git\
	make\
	xz\
	gcc\
	lua lua-devel luarocks\
 && date --iso-8601=ns
